version: "3.1"

services:
  backend:
    env_file: "./.env"
    build:
      context: ./Back_Node.js
      dockerfile: ./Dockerfile
    restart: always
    environment:
      REACT_APP_FRONT_PORT: 5001
    ports:
      - "5000:8000"
    networks:
      - net-ex

  frontend:
    build:
      context: ./Front_React_Redux
      dockerfile: ./Dockerfile
    environment:
      REACT_APP_BACK_PORT: 5000
    ports:
      - "5001:3000"
    networks:
      - net-ex

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - net-ex

networks:
  net-ex:
    driver: bridge
