export const REGISTRATION_USER_SUCCES = "REGISTRATION_USER_SUCCES";
export const REGISTRATION_USER_FAIL = "REGISTRATION_USER_FAIL";
export const CLEAR_ERROR_REGISTRATION = "CLEAR_ERROR_REGISTRATION";
export const LOGIN_USER_SUCCES = "LOGIN_USER_SUCCES";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const CLEAR_ERROR_LOGIN = "CLEAR_ERROR_LOGIN";
export const LOGOUT_USER = "LOGOUT_USER";
