export const GET_LIST_FM_RADIO_LIST = "GET_LIST_FM_RADIO_LIST";
export const ERROR_FETCH = "ERROR_FETCH";
export const GET_ARTIST_INFO_ALBUM = "GET_ARTIST_INFO_ALBUM";
export const GET_TRACKS_INFO_ALBUM = "GET_TRACKS_INFO_ALBUM";
export const GET_TRACK_HISTORY = "GET_TRACK_HISTORY";
export const TRACK_HISTORY_FAIL = "TRACK_HISTORY_FAIL";
